Creaciòn de carpeta Fixes y nueva variable en la estructura PopularMovieEntity llamado votes de tipo Double
JesDev5/MovieApp_Viper pull request #5
Opened 2024-11-01 16:51 UTC by JesDev5

Se crea la carpeta Fixes y la nueva variable llamado votes de tipo Double, con el fin de que la API PUEDA visualizar el promedio de los votos que tienen las peliculas.

2024-11-01 18:44 UTC, maikytech commented
Debes cambiar el nombre del PR, mas corto y conciso, algo como : FIXED: Agregar variable en Entity PopularMovieEntity

2024-11-01 18:46 UTC, maikytech commented
Debes modificar la base del PR, estas apunando a main, debes apuntar a develop

2024-11-01 18:48 UTC, maikytech requested changes
Debes arreglar esos dos comentarios importantes

2024-11-01 19:11 UTC, maikytech commented on MovieApp_Viper/MovieApp_Viper/Entity/PopularMovieEntity.swift
> +        case votes
En la respuesta del servicio no existe votes, tengo entendido que es "vote_average", deberia quedar asi: 

case votes = "vote_average"

2024-11-01 19:43 UTC, maikytech commented on MovieApp_Viper/MovieApp_Viper/Entity/PopularMovieEntity.swift
>      }
Alli debes corregir el Enum, el cual debe estar dentro de la Estructura para que funcione el Coding Key, lo dejaste por fuera, quitale el private, no lo necesita porque el Enum esta en el ambito de la Estrutura

2024-11-05 16:46 UTC, JesDev5 commented on MovieApp_Viper/MovieApp_Viper/Entity/PopularMovieEntity.swift
>      }
done

2024-11-05 16:46 UTC, maikytech approved these changes

2024-11-05 16:48 UTC, merged